import * as THREE from './vendor/three.module.min.js';

const VERSION='0.70.0',SAVE_KEY='orbit04-third-person-v1',TAU=Math.PI*2,MAX_ENEMIES=560,MAX_BULLETS=1200,MAX_HOSTILE_BULLETS=700,ARENA_RADIUS=88;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),choice=a=>a[(Math.random()*a.length)|0],fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`;

document.body.innerHTML=`
<main id="app3d">
  <canvas id="viewport3d" aria-label="ORBIT//04 third-person 3D game"></canvas><div id="spaceFade"></div>
  <div class="ui3d">
    <div id="hud3d" class="hud3d hidden">
      <div class="hudTop3d"><div class="telemetry"><div class="eyebrow">FRAME INTEGRITY</div><div id="hullText3d" class="bigStat">100 / 100</div><div class="bar3d red"><i id="hullFill3d"></i></div><div id="buildText3d" class="subStat">PULSE ARRAY · MK I</div></div>
      <div class="telemetry right"><div class="eyebrow">SECTOR TELEMETRY</div><div id="timeText3d" class="bigStat">00:00 · THREAT 01</div><div id="scoreText3d" class="subStat">0 KILLS · 0 SCORE · 0 SALVAGE</div></div></div>
      <div id="boss3d" class="hidden"><span id="bossName3d">NULL TITAN</span><div class="bar3d red"><i id="bossFill3d"></i></div></div>
      <div id="reticle3d"></div><div id="event3d"></div>
      <div id="flow3d"><div class="eyebrow">REACTOR FLOW</div><div id="flowText3d">0% · BUILD MOMENTUM</div><div class="bar3d amber"><i id="flowFill3d" style="width:0"></i></div></div>
      <div id="combo3d"><div id="comboNumber3d" class="comboNumber">0</div><div class="eyebrow">KILL CHAIN</div></div>
      <div id="xpRail3d"><span id="xpText3d">LEVEL 1 · 0 / 12 DATA</span><div class="bar3d"><i id="xpFill3d" style="width:0"></i></div></div>
    </div>

    <section id="menu3d" class="overlay3d"><div class="panel3d">
      <div class="brand3d"><h1>ORBIT<span>//04</span></h1><div class="version3d">REENTRY BUILD ${VERSION}<br>THIRD-PERSON ENGINE</div></div>
      <div class="menuGrid3d"><div class="heroBlock3d"><p class="lead3d">Przebijaj się przez setki jednostek w pełnym 3D. Statek atakuje automatycznie — Ty odpowiadasz za ruch, pozycję, dash i budowę przeciążonego arsenału.</p><div class="controls3d"><b>WASD</b> RUCH · <b>MYSZ</b> KAMERA · <b>SHIFT</b> DASH · <b>ESC</b> PAUZA</div></div>
      <div class="menuActions3d"><button id="start3d" class="button3d primary"><b>URUCHOM RUN</b><span>8 minut eskalacji · bossowie · nieskończone synergie</span></button><button id="settingsBtn3d" class="button3d"><b>USTAWIENIA</b><span>Grafika, muzyka i efekty</span></button><div class="telemetry"><div class="eyebrow">PROFIL PILOTA</div><div id="profileText3d" class="bigStat">0 SALVAGE</div><div id="recordText3d" class="subStat">BEST 0 · RUNS 0</div></div></div></div>
      <div id="metaGrid3d" class="metaGrid3d"></div>
    </div></section>

    <section id="upgrade3d" class="overlay3d hidden"><div class="panel3d"><div class="brand3d"><div><div class="eyebrow">LIVE SYSTEM INTEGRATION</div><h2 id="upgradeTitle3d">LEVEL 2</h2></div><div class="version3d">NO CARDS<br>CHOOSE ONE SYSTEM</div></div><div id="choices3d" class="choiceGrid3d"></div></div></section>
    <section id="pause3d" class="overlay3d hidden"><div class="panel3d panelSmall3d"><div class="eyebrow">TRANSMISSION SUSPENDED</div><h2>PAUZA</h2><p class="lead3d">Run czeka. Kamera wróci po wznowieniu.</p><div class="row3d"><button id="resume3d" class="button3d primary">WZNÓW</button><button id="abort3d" class="button3d">ZAKOŃCZ RUN</button></div></div></section>
    <section id="gameover3d" class="overlay3d hidden"><div class="panel3d panelSmall3d"><div class="eyebrow">RUN TELEMETRY</div><div id="grade3d" class="grade3d">B</div><h2 id="endTitle3d">FRAME LOST</h2><div id="metrics3d" class="metricGrid3d"></div><p id="reward3d" class="lead3d accent3d"></p><div class="row3d"><button id="retry3d" class="button3d primary">JESZCZE RAZ</button><button id="menuBtn3d" class="button3d">HANGAR</button></div></div></section>
    <section id="settings3d" class="overlay3d hidden"><div class="panel3d panelSmall3d"><div class="eyebrow">DISPLAY / AUDIO</div><h2>USTAWIENIA</h2><div class="settings3d">
      <div class="setting3d"><label for="quality3d">JAKOŚĆ GRAFIKI</label><select id="quality3d"><option>HIGH</option><option>ULTRA</option><option>LOW</option></select></div>
      <div class="setting3d"><label for="music3d">MUZYKA</label><input id="music3d" type="range" min="0" max="100" step="5"></div>
      <div class="setting3d"><label for="sfx3d">EFEKTY</label><input id="sfx3d" type="range" min="0" max="100" step="5"></div>
      <div class="setting3d"><label for="shake3d">DRGANIA KAMERY</label><input id="shake3d" type="checkbox"></div>
    </div><button id="settingsClose3d" class="button3d primary">ZAPISZ I WRÓĆ</button></div></section>
  </div>
</main>`;

const $=id=>document.getElementById(id),show=id=>$(id).classList.remove('hidden'),hide=id=>$(id).classList.add('hidden');
const DEFAULT_PROFILE={salvage:0,bestScore:0,bestTime:0,runs:0,totalKills:0,meta:{hull:0,output:0,thrusters:0},settings:{quality:'HIGH',music:65,sfx:85,shake:true}};
function loadProfile(){try{const raw=JSON.parse(localStorage.getItem(SAVE_KEY)||'{}');return{...DEFAULT_PROFILE,...raw,meta:{...DEFAULT_PROFILE.meta,...(raw.meta||{})},settings:{...DEFAULT_PROFILE.settings,...(raw.settings||{})}}}catch{return structuredClone(DEFAULT_PROFILE)}}
let profile=loadProfile();const persist=()=>localStorage.setItem(SAVE_KEY,JSON.stringify(profile));

class SoundDirector{
  constructor(){this.sfxPools={};this.sfxCursor={};this.music={};this.started=false;this.paused=false;this.paths={pulse:'assets/audio/pulse.wav',kill:'assets/audio/kill.wav',hit:'assets/audio/player_hit.wav',explosion:'assets/audio/explosion.wav',pickup:'assets/audio/pickup.wav',level:'assets/audio/level_up.wav',start:'assets/audio/run_start.wav',boss:'assets/audio/boss_warning.wav',dash:'assets/audio/rush_start.wav',overdrive:'assets/audio/rush_start.wav',ui:'assets/audio/ui_click.wav'};for(const [name,path] of Object.entries(this.paths)){this.sfxPools[name]=Array.from({length:name==='pulse'?8:4},()=>{const a=new Audio(path);a.preload='auto';return a});this.sfxCursor[name]=0}for(const mode of ['exploration','combat','boss']){const a=new Audio(`assets/audio/music_${mode}.wav`);a.loop=true;a.preload='auto';a.volume=0;a._gain=0;this.music[mode]=a}}
  begin(){if(this.started){this.resume();return}this.started=true;for(const track of Object.values(this.music)){track.currentTime=0;track.play().catch(()=>{})}}
  play(name,volume=1,rate=1){const pool=this.sfxPools[name];if(!pool)return;const i=this.sfxCursor[name]++%pool.length,a=pool[i];try{a.pause();a.currentTime=0;a.volume=clamp(volume*profile.settings.sfx/100,0,1);a.playbackRate=rate;a.play().catch(()=>{})}catch{}}
  update(info){if(!this.started||this.paused)return;const intense=info.overdrive>0||info.threat>=4||info.combo>=24,target=info.boss?{exploration:.03,combat:.16,boss:.82}:intense?{exploration:.06,combat:.78,boss:0}:{exploration:.66,combat:.08,boss:0},base=profile.settings.music/100;for(const [key,track] of Object.entries(this.music)){track._gain+=(target[key]-track._gain)*.035;track.volume=clamp(track._gain*base,0,1)}}
  pause(){this.paused=true;for(const track of Object.values(this.music))track.pause()}
  resume(){if(!this.started)return;this.paused=false;for(const track of Object.values(this.music))track.play().catch(()=>{})}
  stop(){this.paused=false;for(const track of Object.values(this.music)){track.pause();track.currentTime=0;track._gain=0}}
}
const SOUND=new SoundDirector();

const UPGRADES=[
  {id:'output',name:'AMPLIFIER CORE',desc:'+24% obrażeń wszystkich systemów.',max:8,apply:s=>s.damage*=1.24},
  {id:'overclock',name:'ZERO-LATENCY BUS',desc:'+18% szybkostrzelności automatycznego uzbrojenia.',max:8,apply:s=>s.fireRate*=1.18},
  {id:'multishot',name:'SPLIT ARRAY',desc:'+1 równoległy pocisk. Szersze pokrycie hordy.',max:5,apply:s=>s.multishot++},
  {id:'velocity',name:'MASS DRIVER',desc:'+22% prędkości pocisków i +1 przebicie.',max:6,apply:s=>{s.projectileSpeed*=1.22;s.pierce++}},
  {id:'hull',name:'REACTIVE HULL',desc:'+28 maksymalnej integralności i natychmiastowa naprawa.',max:6,apply:s=>{s.maxHull+=28;s.hull=Math.min(s.maxHull,s.hull+38)}},
  {id:'thrusters',name:'VECTOR THRUST',desc:'+12% prędkości i krótszy cooldown dasha.',max:6,apply:s=>{s.speed*=1.12;s.dashMax=Math.max(1.5,s.dashMax*.90)}},
  {id:'magnet',name:'GRAVITY NET',desc:'+30% zasięgu zbierania danych.',max:5,apply:s=>s.magnet*=1.30},
  {id:'critical',name:'PREDICTIVE LOCK',desc:'+7% szansy na trafienie krytyczne.',max:6,apply:s=>s.crit+=.07},
  {id:'drone',name:'GUARDIAN WING',desc:'+1 autonomiczny dron orbitalny.',max:4,apply:s=>s.drones++},
  {id:'nova',name:'NOVA REACTOR',desc:'Cykliczna fala uderzeniowa. Kolejne poziomy skracają ładowanie.',max:5,apply:s=>{s.novaLevel++;s.novaMax=Math.max(3.5,8-s.novaLevel*.8)}},
  {id:'shield',name:'PHASE SHIELD',desc:'Regeneracja kadłuba po 5 sekundach bez trafienia.',max:4,apply:s=>s.regen+=2.2},
  {id:'salvage',name:'HARVEST PROTOCOL',desc:'+30% salvage z elit i bossów.',max:4,apply:s=>s.salvageMul*=1.30}
];

function canvasGlow(color='#8de9ff'){
  const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d'),g=x.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,'#ffffff');g.addColorStop(.12,color);g.addColorStop(.48,`${color}66`);g.addColorStop(1,'transparent');x.fillStyle=g;x.fillRect(0,0,128,128);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;
}

class Orbit3D{
  constructor(){
    this.canvas=$('viewport3d');this.renderer=new THREE.WebGLRenderer({canvas:this.canvas,antialias:true,powerPreference:'high-performance'});this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.12;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFShadowMap;
    this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x01040a);this.scene.fog=new THREE.FogExp2(0x020712,.0105);this.camera=new THREE.PerspectiveCamera(64,1,.1,650);this.timer=new THREE.Timer().connect(document);this.keys=new Set();this.cameraYaw=0;this.cameraPitch=.28;this.shake=0;this.mode='menu';this.paused=false;this.leveling=false;this.run=null;this.enemies=[];this.bullets=[];this.hostileBullets=[];this.orbs=[];this.effects=[];this.enemyGrid=new Map();this.tmp=new THREE.Object3D();this.v3=new THREE.Vector3();this.pointerWasLocked=false;this.lastPulseSound=0;
    this.createEnvironment();this.ship=this.createShip();this.scene.add(this.ship);this.createPools();this.bindInput();this.applyQuality();this.resize();addEventListener('resize',()=>this.resize());this.renderProfile();this.camera.position.set(0,8,16);this.camera.lookAt(0,0,0);this.animate();
    this.canvas.dataset.engine='three-0.185-third-person';this.canvas.dataset.renderer='webgl';console.info(`[ORBIT] Three.js ${THREE.REVISION} / third-person / instanced-horde / adaptive-3-stem`);
  }

  createEnvironment(){
    this.scene.add(new THREE.HemisphereLight(0x9adfff,0x07101d,1.5));const sun=new THREE.DirectionalLight(0xd9f6ff,2.3);sun.position.set(-16,24,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-45;sun.shadow.camera.right=45;sun.shadow.camera.top=45;sun.shadow.camera.bottom=-45;this.scene.add(sun);
    this.shipLight=new THREE.PointLight(0x54ddff,8,22,2);this.scene.add(this.shipLight);
    const starPos=[],starCol=[];for(let i=0;i<4600;i++){const r=rand(90,310),a=rand(0,TAU),y=rand(-90,150);starPos.push(Math.cos(a)*r,y,Math.sin(a)*r);const c=Math.random()>.88?new THREE.Color(0x9de8ff):new THREE.Color(0x8b9fb7);starCol.push(c.r,c.g,c.b)}const sg=new THREE.BufferGeometry();sg.setAttribute('position',new THREE.Float32BufferAttribute(starPos,3));sg.setAttribute('color',new THREE.Float32BufferAttribute(starCol,3));this.stars=new THREE.Points(sg,new THREE.PointsMaterial({size:.42,vertexColors:true,transparent:true,opacity:.76,sizeAttenuation:true}));this.scene.add(this.stars);
    this.grid=new THREE.GridHelper(220,55,0x3a9bb8,0x17394d);this.grid.position.y=-3.2;this.grid.material.transparent=true;this.grid.material.opacity=.20;this.scene.add(this.grid);
    for(const r of [24,48,72]){const curve=new THREE.EllipseCurve(0,0,r,r,0,TAU),points=curve.getPoints(160).map(p=>new THREE.Vector3(p.x,-3.12,p.y)),geo=new THREE.BufferGeometry().setFromPoints(points),line=new THREE.LineLoop(geo,new THREE.LineBasicMaterial({color:0x3d9ab7,transparent:true,opacity:.11}));this.scene.add(line)}
    const rockGeo=new THREE.IcosahedronGeometry(1,1),rockMat=new THREE.MeshStandardMaterial({color:0x26323e,roughness:.86,metalness:.22});this.asteroids=new THREE.InstancedMesh(rockGeo,rockMat,230);this.asteroids.receiveShadow=true;for(let i=0;i<230;i++){const a=rand(0,TAU),r=rand(32,180);this.tmp.position.set(Math.cos(a)*r,rand(-18,32),Math.sin(a)*r);this.tmp.rotation.set(rand(0,TAU),rand(0,TAU),rand(0,TAU));const s=rand(.35,2.8);this.tmp.scale.set(s,s*rand(.55,1.25),s*rand(.65,1.5));this.tmp.updateMatrix();this.asteroids.setMatrixAt(i,this.tmp.matrix)}this.scene.add(this.asteroids);
    this.backdrops={};const loader=new THREE.TextureLoader();for(const [key,file] of Object.entries({deep:'assets/visuals/deep-space-arena-v1.png',pulsar:'assets/visuals/space-pulsar-v1.png',rift:'assets/visuals/space-rift-v1.png',supernova:'assets/visuals/space-supernova-v1.png'})){loader.load(file,t=>{t.colorSpace=THREE.SRGBColorSpace;this.backdrops[key]=t;if(key==='deep')this.scene.background=t})}
    this.celestial=new THREE.Group();this.scene.add(this.celestial);const glow=canvasGlow('#7de8ff');this.pulsar=new THREE.Sprite(new THREE.SpriteMaterial({map:glow,color:0xbcefff,transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}));this.pulsar.position.set(0,62,-150);this.pulsar.scale.set(34,34,1);this.celestial.add(this.pulsar);
    this.supernova=new THREE.Sprite(new THREE.SpriteMaterial({map:canvasGlow('#ffd18a'),color:0xffd49a,transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}));this.supernova.position.set(115,24,-165);this.supernova.scale.set(68,68,1);this.celestial.add(this.supernova);
    this.rift=new THREE.Mesh(new THREE.TorusGeometry(20,1.2,12,96),new THREE.MeshBasicMaterial({color:0x8c72ff,transparent:true,opacity:.32,blending:THREE.AdditiveBlending,depthWrite:false}));this.rift.position.set(-92,14,-145);this.celestial.add(this.rift);this.setBackdrop('deep',true);
  }

  createShip(){
    const g=new THREE.Group(),hull=new THREE.MeshPhysicalMaterial({color:0xdcecf2,metalness:.74,roughness:.25,clearcoat:.55,clearcoatRoughness:.18,side:THREE.DoubleSide}),dark=new THREE.MeshStandardMaterial({color:0x101821,metalness:.88,roughness:.22}),cyan=new THREE.MeshStandardMaterial({color:0x3ee0ff,emissive:0x2ac8ff,emissiveIntensity:3.1,metalness:.3,roughness:.18});
    const body=new THREE.Mesh(new THREE.ConeGeometry(.78,3.8,7),hull);body.rotation.x=-Math.PI/2;body.position.z=-.25;body.castShadow=true;g.add(body);
    const core=new THREE.Mesh(new THREE.CapsuleGeometry(.38,1.35,5,10),dark);core.rotation.x=-Math.PI/2;core.position.set(0,.12,.35);core.castShadow=true;g.add(core);
    const wingGeo=new THREE.BufferGeometry();wingGeo.setAttribute('position',new THREE.Float32BufferAttribute([-.22,0,.45,-2.25,0,1.05,-1.18,0,-1.0,.22,0,.45,2.25,0,1.05,1.18,0,-1.0],3));wingGeo.setIndex([0,1,2,3,4,5]);wingGeo.computeVertexNormals();const wings=new THREE.Mesh(wingGeo,hull);wings.position.y=-.03;wings.castShadow=true;g.add(wings);
    const canopy=new THREE.Mesh(new THREE.SphereGeometry(.38,16,10),cyan);canopy.scale.set(.75,.48,1.45);canopy.position.set(0,.48,-.48);g.add(canopy);
    const glow=canvasGlow('#55ddff');g.userData.thrusters=[];for(const x of [-.42,.42]){const engine=new THREE.Mesh(new THREE.CylinderGeometry(.18,.24,.75,10),dark);engine.rotation.x=Math.PI/2;engine.position.set(x,-.06,1.18);g.add(engine);const flame=new THREE.Sprite(new THREE.SpriteMaterial({map:glow,color:0x55ddff,transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}));flame.position.set(x,-.05,1.72);flame.scale.set(.55,1.7,1);g.add(flame);g.userData.thrusters.push(flame)}
    g.scale.setScalar(1.15);g.position.y=0;return g;
  }

  createPools(){
    const configs={scout:[new THREE.IcosahedronGeometry(.72,0),0xff5d79,340],charger:[new THREE.ConeGeometry(.68,1.8,5),0xffb35d,150],tank:[new THREE.DodecahedronGeometry(1,0),0xc185ff,70]};this.enemyMeshes={};for(const [key,[geo,col,max]] of Object.entries(configs)){const mat=new THREE.MeshStandardMaterial({color:0xffffff,emissive:col,emissiveIntensity:.65,metalness:.72,roughness:.31});const mesh=new THREE.InstancedMesh(geo,mat,max);mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);mesh.castShadow=true;mesh.frustumCulled=false;this.enemyMeshes[key]=mesh;this.scene.add(mesh)}
    const bulletMat=new THREE.MeshStandardMaterial({color:0xe8fdff,emissive:0x66e5ff,emissiveIntensity:5,roughness:.12,metalness:.18});this.bulletMesh=new THREE.InstancedMesh(new THREE.SphereGeometry(.13,8,6),bulletMat,MAX_BULLETS);this.bulletMesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.bulletMesh.frustumCulled=false;this.scene.add(this.bulletMesh);
    const hostileMat=new THREE.MeshStandardMaterial({color:0xff9aaa,emissive:0xff244d,emissiveIntensity:4.2});this.hostileMesh=new THREE.InstancedMesh(new THREE.SphereGeometry(.18,8,6),hostileMat,MAX_HOSTILE_BULLETS);this.hostileMesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.hostileMesh.frustumCulled=false;this.scene.add(this.hostileMesh);
    const orbMat=new THREE.MeshStandardMaterial({color:0x9ffff0,emissive:0x38e8cb,emissiveIntensity:3,metalness:.32,roughness:.2});this.orbMesh=new THREE.InstancedMesh(new THREE.OctahedronGeometry(.28,0),orbMat,900);this.orbMesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.orbMesh.frustumCulled=false;this.scene.add(this.orbMesh);
    this.droneGroup=new THREE.Group();this.scene.add(this.droneGroup);for(let i=0;i<4;i++){const d=new THREE.Mesh(new THREE.OctahedronGeometry(.34,0),new THREE.MeshStandardMaterial({color:0xcffff4,emissive:0x58efcd,emissiveIntensity:2.8,metalness:.6,roughness:.2}));d.visible=false;this.droneGroup.add(d)}
  }

  bindInput(){
    addEventListener('keydown',e=>{this.keys.add(e.code);if(e.code==='KeyP'&&this.mode==='run'&&!this.leveling)this.togglePause();if(e.code==='ShiftLeft'||e.code==='ShiftRight')this.tryDash()});addEventListener('keyup',e=>this.keys.delete(e.code));
    this.canvas.addEventListener('click',()=>{if(this.mode==='run'&&!this.paused&&!this.leveling)this.lockPointer()});
    addEventListener('mousemove',e=>{if(document.pointerLockElement===this.canvas){this.cameraYaw-=e.movementX*.00225;this.cameraPitch=clamp(this.cameraPitch-e.movementY*.0014,.12,.48)}});
    document.addEventListener('pointerlockchange',()=>{const locked=document.pointerLockElement===this.canvas;if(this.pointerWasLocked&&!locked&&this.mode==='run'&&!this.leveling&&!this.paused)this.togglePause(true);this.pointerWasLocked=locked});
  }

  lockPointer(){try{this.canvas.requestPointerLock?.()?.catch?.(()=>{})}catch{}}

  applyQuality(){const q=profile.settings.quality,dpr=q==='ULTRA'?Math.min(devicePixelRatio,2):q==='LOW'?1:Math.min(devicePixelRatio,1.5);this.renderer.setPixelRatio(dpr);this.renderer.shadowMap.enabled=q!=='LOW';this.renderer.toneMappingExposure=q==='ULTRA'?1.18:1.08;this.resize()}
  resize(){const w=innerWidth,h=innerHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}
  renderProfile(){$('profileText3d').textContent=`${profile.salvage} SALVAGE`;$('recordText3d').textContent=`BEST ${Math.floor(profile.bestScore)} · RUNS ${profile.runs} · KILLS ${profile.totalKills}`;const names={hull:['HULL MEMORY','+8 startowego kadłuba'],output:['OUTPUT MEMORY','+4% obrażeń'],thrusters:['THRUSTER MEMORY','+3% prędkości']};$('metaGrid3d').innerHTML=Object.entries(names).map(([id,[name,desc]])=>{const l=profile.meta[id],cost=50+l*65;return`<div class="metaUpgrade3d"><b>${name} · M${l}</b><small>${desc} na poziom.</small><button class="button3d" data-meta="${id}" ${l>=5||profile.salvage<cost?'disabled':''}>${l>=5?'MAX':`ULEPSZ · ${cost}`}</button></div>`}).join('');document.querySelectorAll('[data-meta]').forEach(b=>b.onclick=()=>this.buyMeta(b.dataset.meta))}
  buyMeta(id){const l=profile.meta[id],cost=50+l*65;if(l>=5||profile.salvage<cost)return;profile.salvage-=cost;profile.meta[id]++;persist();SOUND.play('ui',.55);this.renderProfile()}

  startRun(){
    SOUND.begin();SOUND.play('start',.78);this.mode='run';this.paused=false;this.leveling=false;this.enemies=[];this.bullets=[];this.hostileBullets=[];this.orbs=[];for(const e of this.effects)this.scene.remove(e.mesh);this.effects=[];this.ship.position.set(0,0,0);this.ship.rotation.set(0,0,0);this.cameraYaw=0;
    this.run={time:0,level:1,xp:0,xpNeed:12,hull:100+profile.meta.hull*8,maxHull:100+profile.meta.hull*8,damage:16*(1+profile.meta.output*.04),fireRate:2.4,projectileSpeed:34,multishot:1,pierce:0,speed:12*(1+profile.meta.thrusters*.03),magnet:7.5,crit:.05,drones:0,novaLevel:0,nova:5,novaMax:8,regen:0,salvageMul:1,dash:0,dashMax:3.5,iframes:0,lastHit:0,fire:0,droneFire:0,spawn:0,nextElite:28,nextBoss:120,boss:null,kills:0,score:0,salvage:0,combo:0,comboBest:0,comboTimer:0,flow:0,overdrive:0,threat:1,levels:{},sector:'DEEP',sectorIndex:0};
    hide('menu3d');hide('gameover3d');hide('pause3d');hide('upgrade3d');show('hud3d');this.setBackdrop('deep');this.message('REENTRY CONFIRMED\nBUILD MOMENTUM · BREAK THE HORDE',1500);this.lockPointer();
  }
  toMenu(){this.mode='menu';this.paused=false;this.leveling=false;this.run=null;SOUND.stop();hide('hud3d');hide('pause3d');hide('gameover3d');hide('upgrade3d');show('menu3d');this.setBackdrop('deep');this.renderProfile();document.exitPointerLock?.()}
  togglePause(force=false){if(this.mode!=='run'||this.leveling)return;this.paused=force||!this.paused;if(this.paused){show('pause3d');SOUND.pause();document.exitPointerLock?.()}else{hide('pause3d');SOUND.resume();this.lockPointer()}}
  tryDash(){const s=this.run;if(this.mode!=='run'||this.paused||this.leveling||!s||s.dash>0)return;const move=this.moveVector();if(move.lengthSq()<.01)return;s.dash=s.dashMax;s.iframes=.34;this.ship.position.addScaledVector(move,6.5);this.ship.position.x=clamp(this.ship.position.x,-ARENA_RADIUS,ARENA_RADIUS);this.ship.position.z=clamp(this.ship.position.z,-ARENA_RADIUS,ARENA_RADIUS);this.shake=Math.max(this.shake,.24);SOUND.play('dash',.48,1.08);this.addShockwave(this.ship.position.x,this.ship.position.z,0x6fe9ff,3.5)}

  moveVector(){const forward=new THREE.Vector3(-Math.sin(this.cameraYaw),0,-Math.cos(this.cameraYaw)),right=new THREE.Vector3(Math.cos(this.cameraYaw),0,-Math.sin(this.cameraYaw)),v=new THREE.Vector3();if(this.keys.has('KeyW'))v.add(forward);if(this.keys.has('KeyS'))v.sub(forward);if(this.keys.has('KeyD'))v.add(right);if(this.keys.has('KeyA'))v.sub(right);return v.lengthSq()>0?v.normalize():v}
  updatePlayer(dt){const s=this.run,move=this.moveVector(),boost=s.overdrive>0?1.25:1;if(move.lengthSq()){this.ship.position.addScaledVector(move,s.speed*boost*dt);const heading=Math.atan2(move.x,-move.z);this.ship.rotation.y=THREE.MathUtils.lerp(this.ship.rotation.y,heading,1-Math.exp(-dt*9));const side=move.dot(new THREE.Vector3(Math.cos(this.ship.rotation.y),0,-Math.sin(this.ship.rotation.y)));this.ship.rotation.z=THREE.MathUtils.lerp(this.ship.rotation.z,-side*.32,1-Math.exp(-dt*8))}else this.ship.rotation.z*=Math.exp(-dt*7);this.ship.position.x=clamp(this.ship.position.x,-ARENA_RADIUS,ARENA_RADIUS);this.ship.position.z=clamp(this.ship.position.z,-ARENA_RADIUS,ARENA_RADIUS);this.ship.position.y=.18+Math.sin(s.time*3.2)*.08;for(const flame of this.ship.userData.thrusters){const q=.88+Math.sin(s.time*34+flame.position.x)*.18;flame.scale.set(.52,1.5*q*(move.lengthSq()?1.35:1),1)}this.shipLight.position.copy(this.ship.position).add(new THREE.Vector3(0,1,2));s.dash=Math.max(0,s.dash-dt);s.iframes=Math.max(0,s.iframes-dt);s.lastHit+=dt;if(s.regen>0&&s.lastHit>5)s.hull=Math.min(s.maxHull,s.hull+s.regen*dt);s.overdrive=Math.max(0,s.overdrive-dt);s.comboTimer=Math.max(0,s.comboTimer-dt);if(s.comboTimer<=0)s.combo=0}

  spawnEnemy(kind=null,elite=false,boss=false){if(this.enemies.length>=MAX_ENEMIES)return;const s=this.run,a=rand(0,TAU),r=rand(38,58),type=boss?'tank':kind||choice(s.time>170?['scout','charger','tank']:s.time>70?['scout','charger']:['scout']),base=type==='tank'?115:type==='charger'?48:28,scale=(1+s.time*.0055)*(1+s.threat*.045),hp=base*scale*(elite?3.2:1)*(boss?18:1);this.enemies.push({type,x:this.ship.position.x+Math.cos(a)*r,z:this.ship.position.z+Math.sin(a)*r,y:0,hp,maxHp:hp,speed:(type==='tank'?3.4:type==='charger'?6.8:4.7)*(1+s.time*.0016),radius:(type==='tank'?1.15:type==='charger'?.78:.68)*(elite?1.35:1)*(boss?3.1:1),damage:(type==='tank'?20:type==='charger'?14:10)*(1+s.time*.0018),elite,boss,dead:false,shoot:rand(.8,1.8),phase:rand(0,TAU)});if(boss){s.boss=this.enemies.at(-1);SOUND.play('boss',.90);this.message('MASSIVE SIGNATURE\nNULL TITAN ENTERING',1800);this.setBackdrop('supernova');this.shake=.55}}
  updateSpawns(dt){const s=this.run;s.threat=1+Math.floor(s.time/45);s.spawn-=dt;const interval=Math.max(.095,.68-s.time*.00115)/(1+s.threat*.045);if(s.spawn<=0){s.spawn=interval;const n=1+(s.time>150&&Math.random()<.34?1:0)+(s.time>300&&Math.random()<.22?1:0);for(let i=0;i<n;i++)this.spawnEnemy()}if(s.time>=s.nextElite){s.nextElite+=rand(22,30);this.spawnEnemy(null,true)}if(s.time>=s.nextBoss&&!s.boss){s.nextBoss+=150;this.spawnEnemy('tank',true,true)}const sectorIndex=Math.floor(s.time/105);if(sectorIndex!==s.sectorIndex&&!s.boss){s.sectorIndex=sectorIndex;const phases=[['DEEP','deep'],['PULSAR VEIL','pulsar'],['GRAVITY RIFT','rift'],['SUPERNOVA FRONT','supernova']];const [name,key]=phases[sectorIndex%phases.length];s.sector=name;this.setBackdrop(key);this.message(`${name}\nHOSTILE PATTERN SHIFT`,1300)}}

  updateEnemies(dt){const s=this.run,px=this.ship.position.x,pz=this.ship.position.z;for(const e of this.enemies){if(e.dead)continue;const dx=px-e.x,dz=pz-e.z,d=Math.hypot(dx,dz)||1;let speed=e.speed;if(e.type==='charger')speed*=.82+.52*(.5+.5*Math.sin(s.time*2.8+e.phase));if(e.type==='tank'&&d<9)speed*=.35;e.x+=dx/d*speed*dt;e.z+=dz/d*speed*dt;e.y=Math.sin(s.time*3+e.phase)*.28;if((e.type==='tank'||e.elite)&&!e.boss){e.shoot-=dt;if(e.shoot<=0&&d<32){e.shoot=e.type==='tank'?2.1:2.8;this.fireHostile(e,dx/d,dz/d)}}if(e.boss){e.shoot-=dt;if(e.shoot<=0){e.shoot=.72;for(let i=0;i<7;i++){const a=i/7*TAU+s.time*.24;this.fireHostile(e,Math.cos(a),Math.sin(a),.74)}}}if(d<e.radius+1.05){this.hitPlayer(e.damage*dt*2.8);e.x-=dx/d*2*dt;e.z-=dz/d*2*dt}}
    this.buildEnemyGrid();this.syncEnemies();
  }
  fireHostile(e,dx,dz,speedMul=1){if(this.hostileBullets.length>=MAX_HOSTILE_BULLETS)return;this.hostileBullets.push({x:e.x,y:e.y+.25,z:e.z,vx:dx*10*speedMul,vz:dz*10*speedMul,life:6,damage:e.boss?16:10,r:e.boss?.28:.20})}
  buildEnemyGrid(){this.enemyGrid.clear();for(const e of this.enemies){if(e.dead)continue;const key=`${Math.floor(e.x/5)},${Math.floor(e.z/5)}`;if(!this.enemyGrid.has(key))this.enemyGrid.set(key,[]);this.enemyGrid.get(key).push(e)}}
  nearby(x,z){const cx=Math.floor(x/5),cz=Math.floor(z/5),out=[];for(let ix=-1;ix<=1;ix++)for(let iz=-1;iz<=1;iz++){const a=this.enemyGrid.get(`${cx+ix},${cz+iz}`);if(a)out.push(...a)}return out}
  nearest(x=this.ship.position.x,z=this.ship.position.z,max=42){let best=null,bd=max*max;for(const e of this.enemies){if(e.dead)continue;const d=(e.x-x)**2+(e.z-z)**2;if(d<bd){bd=d;best=e}}return best}

  updateWeapons(dt){const s=this.run,target=this.nearest();$('reticle3d').classList.toggle('locked',!!target);s.fire-=dt;const rate=s.fireRate*(s.overdrive>0?1.55:1);if(target&&s.fire<=0){s.fire=1/rate;const angle=Math.atan2(target.x-this.ship.position.x,-(target.z-this.ship.position.z)),shots=s.multishot;for(let i=0;i<shots;i++){const spread=(i-(shots-1)/2)*.095,a=angle+spread,crit=Math.random()<s.crit,damage=s.damage*(crit?2:1);if(this.bullets.length<MAX_BULLETS)this.bullets.push({x:this.ship.position.x,y:.4,z:this.ship.position.z,vx:Math.sin(a)*s.projectileSpeed,vz:-Math.cos(a)*s.projectileSpeed,life:2.1,damage,pierce:s.pierce,r:.16,crit})}const now=performance.now();if(now-this.lastPulseSound>90){SOUND.play('pulse',.25,rand(.94,1.05));this.lastPulseSound=now}}
    s.droneFire-=dt;if(s.drones>0&&target&&s.droneFire<=0){s.droneFire=.72/(s.overdrive>0?1.4:1);for(let i=0;i<s.drones;i++){const d=this.droneGroup.children[i],dx=target.x-d.position.x,dz=target.z-d.position.z,l=Math.hypot(dx,dz)||1;if(this.bullets.length<MAX_BULLETS)this.bullets.push({x:d.position.x,y:d.position.y,z:d.position.z,vx:dx/l*s.projectileSpeed*.9,vz:dz/l*s.projectileSpeed*.9,life:2,damage:s.damage*.62,pierce:0,r:.12})}}
    for(let i=0;i<this.droneGroup.children.length;i++){const d=this.droneGroup.children[i];d.visible=i<s.drones;if(d.visible){const a=s.time*1.5+i/s.drones*TAU;d.position.set(this.ship.position.x+Math.cos(a)*2.6,1.1+Math.sin(a*2)*.25,this.ship.position.z+Math.sin(a)*2.6);d.rotation.y=-a+s.time}}
    s.nova-=dt;if(s.novaLevel>0&&s.nova<=0){s.nova=s.novaMax;const radius=8+s.novaLevel*1.7;for(const e of this.enemies)if(!e.dead&&(e.x-this.ship.position.x)**2+(e.z-this.ship.position.z)**2<radius*radius)this.damageEnemy(e,s.damage*(1.5+s.novaLevel*.35));this.addShockwave(this.ship.position.x,this.ship.position.z,0xb88cff,radius);SOUND.play('explosion',.54,1.12);this.shake=Math.max(this.shake,.22)}}

  updateBullets(dt){for(const b of this.bullets){b.x+=b.vx*dt;b.z+=b.vz*dt;b.life-=dt;if(b.life<=0)continue;for(const e of this.nearby(b.x,b.z)){if(e.dead)continue;const rr=e.radius+b.r;if((e.x-b.x)**2+(e.z-b.z)**2<rr*rr){this.damageEnemy(e,b.damage);if(b.pierce>0)b.pierce--;else{b.life=0;break}}}}this.bullets=this.bullets.filter(b=>b.life>0);
    for(const b of this.hostileBullets){b.x+=b.vx*dt;b.z+=b.vz*dt;b.life-=dt;const rr=b.r+1;if((b.x-this.ship.position.x)**2+(b.z-this.ship.position.z)**2<rr*rr){b.life=0;this.hitPlayer(b.damage)}}this.hostileBullets=this.hostileBullets.filter(b=>b.life>0);this.syncProjectiles()}
  damageEnemy(e,damage){if(e.dead)return;e.hp-=damage;if(e.hp<=0)this.killEnemy(e)}
  killEnemy(e){const s=this.run;e.dead=true;s.kills++;s.combo++;s.comboBest=Math.max(s.comboBest,s.combo);s.comboTimer=3.1;s.flow+=e.boss?55:e.elite?8:2;s.score+=(e.boss?5000:e.elite?480:70)*(1+Math.min(3,s.combo*.035));const orbCount=e.boss?22:e.elite?5:1;for(let i=0;i<orbCount;i++)this.orbs.push({x:e.x+rand(-1.6,1.6),y:.3,z:e.z+rand(-1.6,1.6),value:e.boss?4:e.elite?2:1,phase:rand(0,TAU)});this.addExplosion(e.x,e.z,e.boss?0xff5575:e.elite?0xffc36f:0x70efff,e.boss?5:e.elite?2.4:1.25);SOUND.play(e.boss?'explosion':'kill',e.boss?.90:.22,e.boss?.82:rand(.94,1.10));if(e.boss){s.salvage+=Math.round(45*s.salvageMul);s.boss=null;this.message('SIGNATURE BROKEN\n+45 SALVAGE · FLOW SURGE',1500);this.setBackdrop(['deep','pulsar','rift','supernova'][s.sectorIndex%4])}if(s.flow>=100){s.flow-=100;s.overdrive=10;SOUND.play('overdrive',.74);this.message('REACTOR OVERDRIVE\nFIRE RATE +55% · THRUST +25%',1400);this.shake=.35}}
  hitPlayer(amount){const s=this.run;if(s.iframes>0)return;s.hull-=amount;s.lastHit=0;s.iframes=.16;this.shake=Math.max(this.shake,.18);SOUND.play('hit',.48);if(s.hull<=0)this.finish(false)}

  updateOrbs(dt){const s=this.run;for(const o of this.orbs){o.phase+=dt*2.5;const dx=this.ship.position.x-o.x,dz=this.ship.position.z-o.z,d=Math.hypot(dx,dz)||1;if(d<s.magnet){const speed=8+(s.magnet-d)*3.5;o.x+=dx/d*speed*dt;o.z+=dz/d*speed*dt}if(d<1.25){o.dead=true;this.gainXp(o.value)}}this.orbs=this.orbs.filter(o=>!o.dead);this.syncOrbs()}
  gainXp(value){const s=this.run;s.xp+=value;SOUND.play('pickup',.12,rand(.96,1.06));if(s.xp>=s.xpNeed&&!this.leveling){s.xp-=s.xpNeed;s.level++;s.xpNeed=Math.floor(s.xpNeed*1.17+5);this.openUpgrade()}}
  openUpgrade(){this.leveling=true;this.paused=true;SOUND.pause();SOUND.play('level',.70);document.exitPointerLock?.();$('upgradeTitle3d').textContent=`LEVEL ${this.run.level}`;const available=UPGRADES.filter(u=>(this.run.levels[u.id]||0)<u.max),offers=[];while(offers.length<Math.min(3,available.length)){const u=choice(available);if(!offers.includes(u))offers.push(u)}$('choices3d').innerHTML=offers.map(u=>`<button class="systemChoice3d" data-upgrade="${u.id}"><span class="kind">SYSTEM UPGRADE</span><div><h3>${u.name}</h3><p>${u.desc}</p></div><span class="level">MK ${(this.run.levels[u.id]||0)+1} / ${u.max}</span></button>`).join('');document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>this.chooseUpgrade(b.dataset.upgrade));show('upgrade3d')}
  chooseUpgrade(id){const u=UPGRADES.find(x=>x.id===id);if(!u)return;this.run.levels[id]=(this.run.levels[id]||0)+1;u.apply(this.run);this.leveling=false;this.paused=false;hide('upgrade3d');SOUND.resume();SOUND.play('ui',.65,1.08);this.lockPointer();this.message(`${u.name}\nSYSTEM ONLINE`,700)}

  addExplosion(x,z,color,size){const mat=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.85,blending:THREE.AdditiveBlending,depthWrite:false}),mesh=new THREE.Mesh(new THREE.IcosahedronGeometry(1,1),mat);mesh.position.set(x,.4,z);this.scene.add(mesh);this.effects.push({mesh,life:.42,max:.42,size,ring:false})}
  addShockwave(x,z,color,size){const mat=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.72,blending:THREE.AdditiveBlending,depthWrite:false}),mesh=new THREE.Mesh(new THREE.TorusGeometry(1,.07,8,64),mat);mesh.rotation.x=Math.PI/2;mesh.position.set(x,-.05,z);this.scene.add(mesh);this.effects.push({mesh,life:.55,max:.55,size,ring:true})}
  updateEffects(dt){for(const e of this.effects){e.life-=dt;const p=1-e.life/e.max,scale=e.size*(e.ring?.2+p:p*.7+.2);e.mesh.scale.setScalar(scale);e.mesh.material.opacity=Math.max(0,e.life/e.max)*(e.ring?.72:.65);e.mesh.rotation.y+=dt*2}for(const e of this.effects)if(e.life<=0){this.scene.remove(e.mesh);e.mesh.geometry.dispose();e.mesh.material.dispose()}this.effects=this.effects.filter(e=>e.life>0)}

  syncEnemies(){const groups={scout:[],charger:[],tank:[]};for(const e of this.enemies)if(!e.dead)groups[e.type].push(e);for(const [type,mesh] of Object.entries(this.enemyMeshes)){const list=groups[type],limit=Math.min(list.length,mesh.instanceMatrix.count);mesh.count=limit;for(let i=0;i<limit;i++){const e=list[i],s=e.radius/(type==='tank'?1.15:type==='charger'?.78:.68);this.tmp.position.set(e.x,e.y,e.z);this.tmp.rotation.set(type==='charger'?Math.PI/2:0,Math.atan2(this.ship.position.x-e.x,-(this.ship.position.z-e.z))+e.phase*.05,0);this.tmp.scale.setScalar(s);this.tmp.updateMatrix();mesh.setMatrixAt(i,this.tmp.matrix);mesh.setColorAt(i,new THREE.Color(e.boss?0xff244e:e.elite?0xffce79:type==='tank'?0xbd82ff:type==='charger'?0xffa45c:0xff5876))}mesh.instanceMatrix.needsUpdate=true;if(mesh.instanceColor)mesh.instanceColor.needsUpdate=true}this.enemies=this.enemies.filter(e=>!e.dead)}
  syncProjectiles(){this.bulletMesh.count=Math.min(this.bullets.length,MAX_BULLETS);for(let i=0;i<this.bulletMesh.count;i++){const b=this.bullets[i];this.tmp.position.set(b.x,b.y,b.z);this.tmp.scale.set(.7,1,2.2);this.tmp.rotation.set(0,Math.atan2(b.vx,-b.vz),0);this.tmp.updateMatrix();this.bulletMesh.setMatrixAt(i,this.tmp.matrix)}this.bulletMesh.instanceMatrix.needsUpdate=true;this.hostileMesh.count=Math.min(this.hostileBullets.length,MAX_HOSTILE_BULLETS);for(let i=0;i<this.hostileMesh.count;i++){const b=this.hostileBullets[i];this.tmp.position.set(b.x,b.y,b.z);this.tmp.scale.setScalar(b.r/.18);this.tmp.updateMatrix();this.hostileMesh.setMatrixAt(i,this.tmp.matrix)}this.hostileMesh.instanceMatrix.needsUpdate=true}
  syncOrbs(){this.orbMesh.count=Math.min(this.orbs.length,900);for(let i=0;i<this.orbMesh.count;i++){const o=this.orbs[i];this.tmp.position.set(o.x,o.y+Math.sin(o.phase)*.28,o.z);this.tmp.rotation.set(o.phase,o.phase*.7,0);this.tmp.scale.setScalar(o.value>1?1.3:1);this.tmp.updateMatrix();this.orbMesh.setMatrixAt(i,this.tmp.matrix)}this.orbMesh.instanceMatrix.needsUpdate=true}

  setBackdrop(key,instant=false){if(this.currentBackdrop===key)return;this.currentBackdrop=key;const fade=$('spaceFade');fade.style.cssText='position:absolute;inset:0;z-index:4;pointer-events:none;background:#02050a;opacity:.48;transition:opacity .75s';setTimeout(()=>{if(this.backdrops[key])this.scene.background=this.backdrops[key];const colors={deep:0x020712,pulsar:0x03101a,rift:0x09051a,supernova:0x16090a};this.scene.fog.color.setHex(colors[key]);fade.style.opacity='0'},instant?0:260);this.pulsar.visible=key==='pulsar';this.rift.visible=key==='rift';this.supernova.visible=key==='supernova'}
  updateEnvironment(dt){const t=this.run?.time||performance.now()/1000;this.stars.rotation.y+=dt*.004;this.asteroids.rotation.y+=dt*.0012;this.pulsar.material.opacity=.45+.25*Math.sin(t*4);this.pulsar.scale.setScalar(30+Math.sin(t*3)*5);this.supernova.material.opacity=.52+.24*Math.sin(t*2.2);this.supernova.scale.setScalar(64+Math.sin(t*1.8)*8);this.rift.rotation.z+=dt*.13;this.rift.scale.setScalar(1+Math.sin(t*1.4)*.06)}
  updateCamera(dt){const target=this.ship.position,forward=new THREE.Vector3(-Math.sin(this.cameraYaw),0,-Math.cos(this.cameraYaw)),desired=target.clone().addScaledVector(forward,-14).add(new THREE.Vector3(0,6.8+this.cameraPitch*5,0)),look=target.clone().addScaledVector(forward,8).add(new THREE.Vector3(0,1.0,0)),factor=1-Math.exp(-dt*5.5);this.camera.position.lerp(desired,factor);if(this.shake>0&&profile.settings.shake){this.camera.position.x+=rand(-this.shake,this.shake);this.camera.position.y+=rand(-this.shake,this.shake);this.shake=Math.max(0,this.shake-dt*1.8)}this.camera.lookAt(look)}

  updateHud(){const s=this.run;if(!s)return;$('hullText3d').textContent=`${Math.ceil(s.hull)} / ${Math.ceil(s.maxHull)}`;$('hullFill3d').style.width=`${clamp(s.hull/s.maxHull*100,0,100)}%`;$('buildText3d').textContent=`PULSE MK ${1+(s.levels.output||0)} · ${s.multishot} SHOT · ${s.drones} DRONES · DASH ${s.dash>0?s.dash.toFixed(1):'READY'}`;$('timeText3d').textContent=`${fmt(s.time)} · THREAT ${String(s.threat).padStart(2,'0')}`;$('scoreText3d').textContent=`${s.kills} KILLS · ${Math.floor(s.score)} SCORE · ${s.salvage} SALVAGE`;$('comboNumber3d').textContent=s.combo;$('flowText3d').textContent=s.overdrive>0?`OVERDRIVE · ${s.overdrive.toFixed(1)}s`:`${Math.floor(s.flow)}% · BUILD MOMENTUM`;$('flowFill3d').style.width=`${s.overdrive>0?100:clamp(s.flow,0,100)}%`;$('xpText3d').textContent=`LEVEL ${s.level} · ${s.xp} / ${s.xpNeed} DATA`;$('xpFill3d').style.width=`${clamp(s.xp/s.xpNeed*100,0,100)}%`;if(s.boss&&!s.boss.dead){show('boss3d');$('bossFill3d').style.width=`${clamp(s.boss.hp/s.boss.maxHp*100,0,100)}%`}else hide('boss3d')}
  message(text,ms=900){const e=$('event3d');e.textContent=text;e.classList.add('show');clearTimeout(this.messageTimer);this.messageTimer=setTimeout(()=>e.classList.remove('show'),ms)}

  diagnostics(){return{version:VERSION,engine:this.canvas.dataset.engine,mode:this.mode,time:this.run?.time||0,level:this.run?.level||0,enemies:this.enemies.length,bullets:this.bullets.length,orbs:this.orbs.length,kills:this.run?.kills||0,renderer:this.renderer.capabilities.isWebGL2?'webgl2':'webgl1'}}

  update(dt){if(this.mode!=='run'||this.paused||this.leveling||!this.run)return;const s=this.run;s.time+=dt;this.updatePlayer(dt);this.updateSpawns(dt);this.updateEnemies(dt);this.updateWeapons(dt);this.updateBullets(dt);this.updateOrbs(dt);this.updateEffects(dt);SOUND.update({boss:!!s.boss,threat:s.threat,combo:s.combo,overdrive:s.overdrive});this.updateHud();if(s.time>=480)this.finish(true)}
  finish(victory,aborted=false){if(this.mode!=='run')return;const s=this.run;this.mode='ended';this.paused=true;SOUND.pause();document.exitPointerLock?.();const earned=Math.round((s.kills*.12+s.level*2+s.salvage)*(victory?1.35:1));profile.salvage+=earned;profile.bestScore=Math.max(profile.bestScore,Math.floor(s.score));profile.bestTime=Math.max(profile.bestTime,Math.floor(s.time));profile.runs++;profile.totalKills+=s.kills;persist();hide('hud3d');hide('pause3d');show('gameover3d');const grade=victory?'S':s.time>300?'A':s.time>180?'B':s.time>90?'C':'D';$('grade3d').textContent=grade;$('endTitle3d').textContent=aborted?'RUN ABORTED':victory?'SECTOR BROKEN':'FRAME LOST';$('metrics3d').innerHTML=[[fmt(s.time),'TIME'],[s.level,'LEVEL'],[s.kills,'KILLS'],[s.comboBest,'BEST CHAIN'],[Math.floor(s.score),'SCORE'],[Object.keys(s.levels).length,'SYSTEMS'],[s.threat,'THREAT'],[s.salvage,'FIELD SALVAGE']].map(([v,k])=>`<div class="metric3d"><b>${v}</b><span>${k}</span></div>`).join('');$('reward3d').textContent=`+${earned} SALVAGE · stałe ulepszenia czekają w hangarze`;this.renderProfile()}

  animate(){requestAnimationFrame(()=>this.animate());this.timer.update();const dt=Math.min(.033,this.timer.getDelta());if(this.mode==='menu'){this.ship.rotation.y+=dt*.16;this.ship.position.y=.2+Math.sin(performance.now()*.0012)*.18;this.camera.position.lerp(new THREE.Vector3(0,5.5,13),1-Math.exp(-dt*2));this.camera.lookAt(0,.3,0)}else{this.update(dt);this.updateCamera(dt)}this.updateEnvironment(dt);this.renderer.render(this.scene,this.camera)}
}

const game=new Orbit3D();
globalThis.__ORBIT3D__=game;
$('start3d').onclick=()=>game.startRun();$('retry3d').onclick=()=>game.startRun();$('menuBtn3d').onclick=()=>game.toMenu();$('resume3d').onclick=()=>game.togglePause();$('abort3d').onclick=()=>game.finish(false,true);
$('settingsBtn3d').onclick=()=>{hide('menu3d');$('quality3d').value=profile.settings.quality;$('music3d').value=profile.settings.music;$('sfx3d').value=profile.settings.sfx;$('shake3d').checked=profile.settings.shake;show('settings3d')};
$('settingsClose3d').onclick=()=>{profile.settings.quality=$('quality3d').value;profile.settings.music=Number($('music3d').value);profile.settings.sfx=Number($('sfx3d').value);profile.settings.shake=$('shake3d').checked;persist();game.applyQuality();hide('settings3d');show('menu3d');SOUND.play('ui',.5)};
